apiVersion: v1
kind: Service
metadata:
  name: nginx-project
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: nginx-project
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-project-2
spec:
  type: NodePort
  ports:
    - port: 81
  selector:
    app: nginx-project-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-project
spec:
  replicas: 20
  selector:
    matchLabels:
      app: nginx-project
  template:
    metadata:
      labels:
        app: nginx-project
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-project-2
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-project-2
  template:
    metadata:
      labels:
        app: nginx-project-2
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 81
